linters:
  enable:
    - asciicheck
    - gocritic
    - goconst
    - goimports
    - gofmt
    - gosec
    - misspell
    - unconvert
    - whitespace
    - promlinter
    - revive
    - staticcheck
