version: "2"
linters:
  default: standard
  enable:
    - asciicheck
    - goconst
    - gocritic
    - gosec
    - misspell
    - unconvert
    - whitespace
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
