name: Release
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-release:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        build: [linux-386, linux-amd64, linux-arm, linux-arm64, darwin-amd64, darwin-arm64, windows-amd64, windows-arm64]
        include:
        - build: linux-386
          platform: ubuntu-latest
          goos: linux
          goarch: 386
          cgo_enabled: 0
        - build: linux-amd64
          platform: ubuntu-latest
          goos: linux
          goarch: amd64
          cgo_enabled: 0
        - build: linux-arm
          platform: ubuntu-latest
          goos: linux
          goarch: arm
          cgo_enabled: 0
        - build: linux-arm64
          platform: ubuntu-latest
          goos: linux
          goarch: arm64
          cgo_enabled: 0
        - build: darwin-amd64
          platform: macos-latest
          goos: darwin
          goarch: amd64
        - build: windows-amd64
          platform: windows-latest
          goos: windows
          goarch: amd64
          cgo_enabled: 0
        - build: windows-arm64
          platform: windows-latest
          goos: windows
          goarch: arm64
          cgo_enabled: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Test
        run: make test
      - name: Set CGO_ENABLED=0 if needed
        if: ${{ matrix.cgo_enabled }}
        run: echo "CGO_ENABLED=0" >> $GITHUB_ENV
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: make build-release
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*
          generate_release_notes: true
